language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - page # build master branch only
script:
  - npm install
  - npm run-script build:test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: page
